// THIS FILE IS AUTOGENERATED BY axi_intercon_gen
// ANY MANUAL CHANGES WILL BE LOST
wire [39:0] AXILite_awaddr;
wire  [2:0] AXILite_awprot;
wire        AXILite_awvalid;
wire        AXILite_awready;
wire [39:0] AXILite_araddr;
wire  [2:0] AXILite_arprot;
wire        AXILite_arvalid;
wire        AXILite_arready;
wire [31:0] AXILite_wdata;
wire  [3:0] AXILite_wstrb;
wire        AXILite_wvalid;
wire        AXILite_wready;
wire  [1:0] AXILite_bresp;
wire        AXILite_bvalid;
wire        AXILite_bready;
wire [31:0] AXILite_rdata;
wire  [1:0] AXILite_rresp;
wire        AXILite_rvalid;
wire        AXILite_rready;
wire [39:0] PLIC_awaddr;
wire  [2:0] PLIC_awprot;
wire        PLIC_awvalid;
wire        PLIC_awready;
wire [39:0] PLIC_araddr;
wire  [2:0] PLIC_arprot;
wire        PLIC_arvalid;
wire        PLIC_arready;
wire [31:0] PLIC_wdata;
wire  [3:0] PLIC_wstrb;
wire        PLIC_wvalid;
wire        PLIC_wready;
wire  [1:0] PLIC_bresp;
wire        PLIC_bvalid;
wire        PLIC_bready;
wire [31:0] PLIC_rdata;
wire  [1:0] PLIC_rresp;
wire        PLIC_rvalid;
wire        PLIC_rready;
wire [39:0] UART0_awaddr;
wire  [2:0] UART0_awprot;
wire        UART0_awvalid;
wire        UART0_awready;
wire [39:0] UART0_araddr;
wire  [2:0] UART0_arprot;
wire        UART0_arvalid;
wire        UART0_arready;
wire [31:0] UART0_wdata;
wire  [3:0] UART0_wstrb;
wire        UART0_wvalid;
wire        UART0_wready;
wire  [1:0] UART0_bresp;
wire        UART0_bvalid;
wire        UART0_bready;
wire [31:0] UART0_rdata;
wire  [1:0] UART0_rresp;
wire        UART0_rvalid;
wire        UART0_rready;
wire [39:0] UART1_awaddr;
wire  [2:0] UART1_awprot;
wire        UART1_awvalid;
wire        UART1_awready;
wire [39:0] UART1_araddr;
wire  [2:0] UART1_arprot;
wire        UART1_arvalid;
wire        UART1_arready;
wire [31:0] UART1_wdata;
wire  [3:0] UART1_wstrb;
wire        UART1_wvalid;
wire        UART1_wready;
wire  [1:0] UART1_bresp;
wire        UART1_bvalid;
wire        UART1_bready;
wire [31:0] UART1_rdata;
wire  [1:0] UART1_rresp;
wire        UART1_rvalid;
wire        UART1_rready;
wire [39:0] SPI0_awaddr;
wire  [2:0] SPI0_awprot;
wire        SPI0_awvalid;
wire        SPI0_awready;
wire [39:0] SPI0_araddr;
wire  [2:0] SPI0_arprot;
wire        SPI0_arvalid;
wire        SPI0_arready;
wire [31:0] SPI0_wdata;
wire  [3:0] SPI0_wstrb;
wire        SPI0_wvalid;
wire        SPI0_wready;
wire  [1:0] SPI0_bresp;
wire        SPI0_bvalid;
wire        SPI0_bready;
wire [31:0] SPI0_rdata;
wire  [1:0] SPI0_rresp;
wire        SPI0_rvalid;
wire        SPI0_rready;
wire [39:0] SPI1_awaddr;
wire  [2:0] SPI1_awprot;
wire        SPI1_awvalid;
wire        SPI1_awready;
wire [39:0] SPI1_araddr;
wire  [2:0] SPI1_arprot;
wire        SPI1_arvalid;
wire        SPI1_arready;
wire [31:0] SPI1_wdata;
wire  [3:0] SPI1_wstrb;
wire        SPI1_wvalid;
wire        SPI1_wready;
wire  [1:0] SPI1_bresp;
wire        SPI1_bvalid;
wire        SPI1_bready;
wire [31:0] SPI1_rdata;
wire  [1:0] SPI1_rresp;
wire        SPI1_rvalid;
wire        SPI1_rready;
wire [39:0] VGA_awaddr;
wire  [2:0] VGA_awprot;
wire        VGA_awvalid;
wire        VGA_awready;
wire [39:0] VGA_araddr;
wire  [2:0] VGA_arprot;
wire        VGA_arvalid;
wire        VGA_arready;
wire [31:0] VGA_wdata;
wire  [3:0] VGA_wstrb;
wire        VGA_wvalid;
wire        VGA_wready;
wire  [1:0] VGA_bresp;
wire        VGA_bvalid;
wire        VGA_bready;
wire [31:0] VGA_rdata;
wire  [1:0] VGA_rresp;
wire        VGA_rvalid;
wire        VGA_rready;
wire [39:0] TIMER_awaddr;
wire  [2:0] TIMER_awprot;
wire        TIMER_awvalid;
wire        TIMER_awready;
wire [39:0] TIMER_araddr;
wire  [2:0] TIMER_arprot;
wire        TIMER_arvalid;
wire        TIMER_arready;
wire [31:0] TIMER_wdata;
wire  [3:0] TIMER_wstrb;
wire        TIMER_wvalid;
wire        TIMER_wready;
wire  [1:0] TIMER_bresp;
wire        TIMER_bvalid;
wire        TIMER_bready;
wire [31:0] TIMER_rdata;
wire  [1:0] TIMER_rresp;
wire        TIMER_rvalid;
wire        TIMER_rready;
wire [39:0] ADC_awaddr;
wire  [2:0] ADC_awprot;
wire        ADC_awvalid;
wire        ADC_awready;
wire [39:0] ADC_araddr;
wire  [2:0] ADC_arprot;
wire        ADC_arvalid;
wire        ADC_arready;
wire [31:0] ADC_wdata;
wire  [3:0] ADC_wstrb;
wire        ADC_wvalid;
wire        ADC_wready;
wire  [1:0] ADC_bresp;
wire        ADC_bvalid;
wire        ADC_bready;
wire [31:0] ADC_rdata;
wire  [1:0] ADC_rresp;
wire        ADC_rvalid;
wire        ADC_rready;
wire [39:0] DAC_awaddr;
wire  [2:0] DAC_awprot;
wire        DAC_awvalid;
wire        DAC_awready;
wire [39:0] DAC_araddr;
wire  [2:0] DAC_arprot;
wire        DAC_arvalid;
wire        DAC_arready;
wire [31:0] DAC_wdata;
wire  [3:0] DAC_wstrb;
wire        DAC_wvalid;
wire        DAC_wready;
wire  [1:0] DAC_bresp;
wire        DAC_bvalid;
wire        DAC_bready;
wire [31:0] DAC_rdata;
wire  [1:0] DAC_rresp;
wire        DAC_rvalid;
wire        DAC_rready;

axi_lite_intercon axi_lite_intercon
   (.clk_i             (clk),
    .rst_ni            (rst_n),
    .i_AXILite_awaddr  (AXILite_awaddr),
    .i_AXILite_awprot  (AXILite_awprot),
    .i_AXILite_awvalid (AXILite_awvalid),
    .o_AXILite_awready (AXILite_awready),
    .i_AXILite_araddr  (AXILite_araddr),
    .i_AXILite_arprot  (AXILite_arprot),
    .i_AXILite_arvalid (AXILite_arvalid),
    .o_AXILite_arready (AXILite_arready),
    .i_AXILite_wdata   (AXILite_wdata),
    .i_AXILite_wstrb   (AXILite_wstrb),
    .i_AXILite_wvalid  (AXILite_wvalid),
    .o_AXILite_wready  (AXILite_wready),
    .o_AXILite_bresp   (AXILite_bresp),
    .o_AXILite_bvalid  (AXILite_bvalid),
    .i_AXILite_bready  (AXILite_bready),
    .o_AXILite_rdata   (AXILite_rdata),
    .o_AXILite_rresp   (AXILite_rresp),
    .o_AXILite_rvalid  (AXILite_rvalid),
    .i_AXILite_rready  (AXILite_rready),
    .o_PLIC_awaddr     (PLIC_awaddr),
    .o_PLIC_awprot     (PLIC_awprot),
    .o_PLIC_awvalid    (PLIC_awvalid),
    .i_PLIC_awready    (PLIC_awready),
    .o_PLIC_araddr     (PLIC_araddr),
    .o_PLIC_arprot     (PLIC_arprot),
    .o_PLIC_arvalid    (PLIC_arvalid),
    .i_PLIC_arready    (PLIC_arready),
    .o_PLIC_wdata      (PLIC_wdata),
    .o_PLIC_wstrb      (PLIC_wstrb),
    .o_PLIC_wvalid     (PLIC_wvalid),
    .i_PLIC_wready     (PLIC_wready),
    .i_PLIC_bresp      (PLIC_bresp),
    .i_PLIC_bvalid     (PLIC_bvalid),
    .o_PLIC_bready     (PLIC_bready),
    .i_PLIC_rdata      (PLIC_rdata),
    .i_PLIC_rresp      (PLIC_rresp),
    .i_PLIC_rvalid     (PLIC_rvalid),
    .o_PLIC_rready     (PLIC_rready),
    .o_UART0_awaddr    (UART0_awaddr),
    .o_UART0_awprot    (UART0_awprot),
    .o_UART0_awvalid   (UART0_awvalid),
    .i_UART0_awready   (UART0_awready),
    .o_UART0_araddr    (UART0_araddr),
    .o_UART0_arprot    (UART0_arprot),
    .o_UART0_arvalid   (UART0_arvalid),
    .i_UART0_arready   (UART0_arready),
    .o_UART0_wdata     (UART0_wdata),
    .o_UART0_wstrb     (UART0_wstrb),
    .o_UART0_wvalid    (UART0_wvalid),
    .i_UART0_wready    (UART0_wready),
    .i_UART0_bresp     (UART0_bresp),
    .i_UART0_bvalid    (UART0_bvalid),
    .o_UART0_bready    (UART0_bready),
    .i_UART0_rdata     (UART0_rdata),
    .i_UART0_rresp     (UART0_rresp),
    .i_UART0_rvalid    (UART0_rvalid),
    .o_UART0_rready    (UART0_rready),
    .o_UART1_awaddr    (UART1_awaddr),
    .o_UART1_awprot    (UART1_awprot),
    .o_UART1_awvalid   (UART1_awvalid),
    .i_UART1_awready   (UART1_awready),
    .o_UART1_araddr    (UART1_araddr),
    .o_UART1_arprot    (UART1_arprot),
    .o_UART1_arvalid   (UART1_arvalid),
    .i_UART1_arready   (UART1_arready),
    .o_UART1_wdata     (UART1_wdata),
    .o_UART1_wstrb     (UART1_wstrb),
    .o_UART1_wvalid    (UART1_wvalid),
    .i_UART1_wready    (UART1_wready),
    .i_UART1_bresp     (UART1_bresp),
    .i_UART1_bvalid    (UART1_bvalid),
    .o_UART1_bready    (UART1_bready),
    .i_UART1_rdata     (UART1_rdata),
    .i_UART1_rresp     (UART1_rresp),
    .i_UART1_rvalid    (UART1_rvalid),
    .o_UART1_rready    (UART1_rready),
    .o_SPI0_awaddr     (SPI0_awaddr),
    .o_SPI0_awprot     (SPI0_awprot),
    .o_SPI0_awvalid    (SPI0_awvalid),
    .i_SPI0_awready    (SPI0_awready),
    .o_SPI0_araddr     (SPI0_araddr),
    .o_SPI0_arprot     (SPI0_arprot),
    .o_SPI0_arvalid    (SPI0_arvalid),
    .i_SPI0_arready    (SPI0_arready),
    .o_SPI0_wdata      (SPI0_wdata),
    .o_SPI0_wstrb      (SPI0_wstrb),
    .o_SPI0_wvalid     (SPI0_wvalid),
    .i_SPI0_wready     (SPI0_wready),
    .i_SPI0_bresp      (SPI0_bresp),
    .i_SPI0_bvalid     (SPI0_bvalid),
    .o_SPI0_bready     (SPI0_bready),
    .i_SPI0_rdata      (SPI0_rdata),
    .i_SPI0_rresp      (SPI0_rresp),
    .i_SPI0_rvalid     (SPI0_rvalid),
    .o_SPI0_rready     (SPI0_rready),
    .o_SPI1_awaddr     (SPI1_awaddr),
    .o_SPI1_awprot     (SPI1_awprot),
    .o_SPI1_awvalid    (SPI1_awvalid),
    .i_SPI1_awready    (SPI1_awready),
    .o_SPI1_araddr     (SPI1_araddr),
    .o_SPI1_arprot     (SPI1_arprot),
    .o_SPI1_arvalid    (SPI1_arvalid),
    .i_SPI1_arready    (SPI1_arready),
    .o_SPI1_wdata      (SPI1_wdata),
    .o_SPI1_wstrb      (SPI1_wstrb),
    .o_SPI1_wvalid     (SPI1_wvalid),
    .i_SPI1_wready     (SPI1_wready),
    .i_SPI1_bresp      (SPI1_bresp),
    .i_SPI1_bvalid     (SPI1_bvalid),
    .o_SPI1_bready     (SPI1_bready),
    .i_SPI1_rdata      (SPI1_rdata),
    .i_SPI1_rresp      (SPI1_rresp),
    .i_SPI1_rvalid     (SPI1_rvalid),
    .o_SPI1_rready     (SPI1_rready),
    .o_VGA_awaddr      (VGA_awaddr),
    .o_VGA_awprot      (VGA_awprot),
    .o_VGA_awvalid     (VGA_awvalid),
    .i_VGA_awready     (VGA_awready),
    .o_VGA_araddr      (VGA_araddr),
    .o_VGA_arprot      (VGA_arprot),
    .o_VGA_arvalid     (VGA_arvalid),
    .i_VGA_arready     (VGA_arready),
    .o_VGA_wdata       (VGA_wdata),
    .o_VGA_wstrb       (VGA_wstrb),
    .o_VGA_wvalid      (VGA_wvalid),
    .i_VGA_wready      (VGA_wready),
    .i_VGA_bresp       (VGA_bresp),
    .i_VGA_bvalid      (VGA_bvalid),
    .o_VGA_bready      (VGA_bready),
    .i_VGA_rdata       (VGA_rdata),
    .i_VGA_rresp       (VGA_rresp),
    .i_VGA_rvalid      (VGA_rvalid),
    .o_VGA_rready      (VGA_rready),
    .o_TIMER_awaddr    (TIMER_awaddr),
    .o_TIMER_awprot    (TIMER_awprot),
    .o_TIMER_awvalid   (TIMER_awvalid),
    .i_TIMER_awready   (TIMER_awready),
    .o_TIMER_araddr    (TIMER_araddr),
    .o_TIMER_arprot    (TIMER_arprot),
    .o_TIMER_arvalid   (TIMER_arvalid),
    .i_TIMER_arready   (TIMER_arready),
    .o_TIMER_wdata     (TIMER_wdata),
    .o_TIMER_wstrb     (TIMER_wstrb),
    .o_TIMER_wvalid    (TIMER_wvalid),
    .i_TIMER_wready    (TIMER_wready),
    .i_TIMER_bresp     (TIMER_bresp),
    .i_TIMER_bvalid    (TIMER_bvalid),
    .o_TIMER_bready    (TIMER_bready),
    .i_TIMER_rdata     (TIMER_rdata),
    .i_TIMER_rresp     (TIMER_rresp),
    .i_TIMER_rvalid    (TIMER_rvalid),
    .o_TIMER_rready    (TIMER_rready),
    .o_ADC_awaddr      (ADC_awaddr),
    .o_ADC_awprot      (ADC_awprot),
    .o_ADC_awvalid     (ADC_awvalid),
    .i_ADC_awready     (ADC_awready),
    .o_ADC_araddr      (ADC_araddr),
    .o_ADC_arprot      (ADC_arprot),
    .o_ADC_arvalid     (ADC_arvalid),
    .i_ADC_arready     (ADC_arready),
    .o_ADC_wdata       (ADC_wdata),
    .o_ADC_wstrb       (ADC_wstrb),
    .o_ADC_wvalid      (ADC_wvalid),
    .i_ADC_wready      (ADC_wready),
    .i_ADC_bresp       (ADC_bresp),
    .i_ADC_bvalid      (ADC_bvalid),
    .o_ADC_bready      (ADC_bready),
    .i_ADC_rdata       (ADC_rdata),
    .i_ADC_rresp       (ADC_rresp),
    .i_ADC_rvalid      (ADC_rvalid),
    .o_ADC_rready      (ADC_rready),
    .o_DAC_awaddr      (DAC_awaddr),
    .o_DAC_awprot      (DAC_awprot),
    .o_DAC_awvalid     (DAC_awvalid),
    .i_DAC_awready     (DAC_awready),
    .o_DAC_araddr      (DAC_araddr),
    .o_DAC_arprot      (DAC_arprot),
    .o_DAC_arvalid     (DAC_arvalid),
    .i_DAC_arready     (DAC_arready),
    .o_DAC_wdata       (DAC_wdata),
    .o_DAC_wstrb       (DAC_wstrb),
    .o_DAC_wvalid      (DAC_wvalid),
    .i_DAC_wready      (DAC_wready),
    .i_DAC_bresp       (DAC_bresp),
    .i_DAC_bvalid      (DAC_bvalid),
    .o_DAC_bready      (DAC_bready),
    .i_DAC_rdata       (DAC_rdata),
    .i_DAC_rresp       (DAC_rresp),
    .i_DAC_rvalid      (DAC_rvalid),
    .o_DAC_rready      (DAC_rready));

